name: Hello Infra Runner

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:


jobs:
  hello:
    runs-on: [infra]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello I am running this job on self hosted runner"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.TENANT_ID }}"
            }

      - name: Print Branch And Run Terraform
        shell: bash
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"

          TFVARS_FILE="${GITHUB_REF_NAME}.tfvars"
          echo "Using tfvars file: $TFVARS_FILE"

          if [[ ! -f "$TFVARS_FILE" ]]; then
            echo "File $TFVARS_FILE not found"
            exit 1
          fi

          echo "Contents of $TFVARS_FILE"
          cat "$TFVARS_FILE"

          terraform --version
          terraform init
          terraform plan -var-file="$TFVARS_FILE"
          terraform apply -var-file="$TFVARS_FILE" --auto-approve
