name: Terraform Deploy by Branch

on:
  push:
    branches:
      - main
      - dev

jobs:
  terraform:
    runs-on: Infra

    # Select environment (prod for main, dev otherwise)
     environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
     
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Terraform vars file
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            echo "TFVARS=main.tfvars" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF_NAME" == "dev" ]]; then
            echo "TFVARS=dev.tfvars" >> $GITHUB_ENV
          else
            echo "Unsupported branch"
            exit 1
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=$TFVARS

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=$TFVARS
